language: go
go_import_path: github.ibm.com/IBMPrivateCloud/configmap-watcher
go:
  - 1.13.2

services:
  - docker

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "LIXM2OUNfxJ4wsIYYhmphzQl4hk3ad8JDh8ggJ/L9dPbKAMSAqd8lY7vCXDMlVRh335VJ3EgqsdH8j+JcFE4W939UzPqmclDLP55dR3ONPiwNXLMU6JQtfiFPbT242vhIWNi1OfMwOPedQLGBzmKcQcku5WDzHWtX+fOkb6SVD1DbUFjiN+Co8eTnO5dJ4M5Kqn8OcGSzzH5DjwAUSpM9x2WHBUU2khRP85l0OQdLCGc/F4aknZ3Ufw4kv06o5Pj+jhVhquZPTELEsJ28BgE3/3qL1PQyqv/P25+VZKcsh9oxnX1JQMK9UXSS2JhhQI+7D+gXSIpJznzO05Q91QokJ0rj1L6lTYTDrIihX2G/5bFmXThdPLFZQL66mx5utLrWli9LqRvuLAaUSpLvH45xmVELsYuKlAFuUbaDBx4m+cHLubP/7lX/i/J2V8UcqmuIFmHgBsq0sb6FlSqk6UkHOaukCPb7DCGTOw5gVXUmyanrGEMXd08d2xyddz/QNMNtC5TdU571emoP9Fwh/A9icqkBPst0oJm9tp3AjQw+evhtHE3vmqr/OGmnTnyrWd89GGe1u3ZXBc8jyTXTnibj7NIy1sw3yNSvYf0NdsOvhSqObiEKQYrMP+z+kgCqdmMCChZ+1ivJvrsOSeuSnaQbFqAxdtYAkbo4GYPS2ipoTo="

env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"
    # Component Specific
    - COMPONENT_TYPE="make"
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/build/install-dependencies.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-unit-tests.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-e2e-tests.sh

stages:
  - build
  - unit-test
  - test-e2e
  - publish

jobs:
  include:
    - stage: build
      name: "Build the image and push"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - |
          make
          make component/build
          make component/push
          make security/scans
    - stage: unit-test
      name: "Build and run unit tests"
      os: linux
      script:
        - |
          make
          make component/test/unit
    - stage: test-e2e
      name: "Run e2e tests"
      os: linux
      script:
        - |
          make
          make component/pull
          make component/test/e2e
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script:
        - |
          make
          make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
