apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cmw
  labels:
    watcher.ibm.com/opt-in: "true"
  annotations:
    watcher.ibm.com/configmap-resource: "cert-manager/test-map"
spec:
  selector:
    matchLabels:
      app: cmw
  template:
    metadata:
      labels:
        app: cmw
    spec:
      imagePullSecrets:
      - name: ps1
      containers:
      - name: cmw
        image: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/crystal/config-map-watcher/cmw:1
        imagePullPolicy: IfNotPresent
      nodeSelector:
        master: "true"
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
          operator: Exists
