apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cmw
spec:
  selector:
    matchLabels:
      app: cmw
  template:
    metadata:
      labels:
        app: cmw
    spec:
      containers:
      - name: cmw
        image: hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/crystal/config-map-watcher/cmw:1
        imagePullPolicy: IfNotPresent
      nodeSelector:
        master: "true"
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
          operator: Exists
