apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cmw
  annotations:
    watcher.ibm.com/configmap-resource: "cert-manager/test-map"
  labels:
    target: configmap-watcher
spec:
  selector:
    matchLabels:
      app: cmw
  template:
    metadata:
      labels:
        app: cmw
    spec:
      containers:
      - name: cmw
        image: hyc-cloud-private-stable-docker-local.artifactory.swg-devops.com/ibmcom-amd64/pause:3.1
        imagePullPolicy: IfNotPresent
      nodeSelector:
        master: "true"
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
          operator: Exists
